---
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: restart controlclaw-agent
  ansible.builtin.systemd:
    name: controlclaw-agent
    state: restarted
    daemon_reload: true
